### ISSUE TITLE
callback failed for Martin Fowler scrum

### ISSUE THREAD

**Issue by tansaku** [AgileVentures/HangoutConnection#30]
![](https://www.dropbox.com/s/dry4x45wthj6t02/Screenshot%202016-09-01%2009.37.19.png?dl=1)

```
jhwidvr33vdp3jqppsn7duw37qe?hl=en:371 MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details.
rs=AGyH-FtJGoRgmeo5wKIWMcZ0VoKMun8wOg:98 The MediaStream 'ended' event is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5730404371791872 for more details.
https://hangouts.google.com/hangouts/_/channel/test?VER=8&TYPE=xmlhttp&zx=igi0e2qytrmv Failed to load resource: the server responded with a status of 401 ()
jhwidvr33vdp3jqppsn7duw37qe?hl=en:1 XMLHttpRequest cannot load https://hangouts.google.com/hangouts/_/channel/test?VER=8&TYPE=xmlhttp&zx=igi0e2qytrmv. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://talkgadget.google.com' is therefore not allowed access. The response had HTTP status code 401.
jhwidvr33vdp3jqppsn7duw37qe?hl=en:433 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
https://images1-hangout-opensocial.googleusercontent.com/gadgets/proxy?url=…2_f0458a7f051f6c3e7934c3f010ef4632.png&resize_h=32&resize_w=32&refresh=967 Failed to load resource: the server responded with a status of 400 ()
rs=AGyH-FtJGoRgmeo5wKIWMcZ0VoKMun8wOg:4390 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
rs=AGyH-FtJGoRgmeo5wKIWMcZ0VoKMun8wOg:4390 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
toolboxv2.js:888 'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.
ifr?url=app%3A%2F%2F135304697558%2Fhangout&container=hangout&view=default&lang=all&country=ALL&debu…:242 Uncaught TypeError: a[c] is not a function
rs=AGyH-Fsuqnj1lbg84GOF9bbhLrzHJQTKhg:42 Caught exception while dispatching event:
TypeError: Cannot read property 'callbackUrl' of null
    at HangoutApplication.sendUrl (https://eq998qatabmpg8td633a9bk8sol8r3nt-a-hangout-opensocial.googleusercon…&parent=https%3A%2F%2Ftalkgadget.google.com&mid=2&authuser=0&hl=en:1466:30)
    at HangoutApplication.sendUrl (https://eq998qatabmpg8td633a9bk8sol8r3nt-a-hangout-opensocial.googleusercon…&parent=https%3A%2F%2Ftalkgadget.google.com&mid=2&authuser=0&hl=en:1404:59)
    at HangoutApplication.initialize (https://eq998qatabmpg8td633a9bk8sol8r3nt-a-hangout-opensocial.googleusercon…&parent=https%3A%2F%2Ftalkgadget.google.com&mid=2&authuser=0&hl=en:1439:14)
    at HangoutApplication.initialize (https://eq998qatabmpg8td633a9bk8sol8r3nt-a-hangout-opensocial.googleusercon…&parent=https%3A%2F%2Ftalkgadget.google.com&mid=2&authuser=0&hl=en:1404:59)
    at uc.a (https://eq998qatabmpg8td633a9bk8sol8r3nt-a-hangout-opensocial.googleusercon…&parent=https%3A%2F%2Ftalkgadget.google.com&mid=2&authuser=0&hl=en:1415:19)
    at uc.handleEvent (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.uBO…k.O/m=platform_stable/rt=j/d=1/rs=AGyH-Fsuqnj1lbg84GOF9bbhLrzHJQTKhg:43:54)
    at yd.a.(anonymous function).a.(anonymous function) (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.uBO….O/m=platform_stable/rt=j/d=1/rs=AGyH-Fsuqnj1lbg84GOF9bbhLrzHJQTKhg:38:390)
    at jc (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.uBO….O/m=platform_stable/rt=j/d=1/rs=AGyH-Fsuqnj1lbg84GOF9bbhLrzHJQTKhg:41:660)
    at E (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.uBO….O/m=platform_stable/rt=j/d=1/rs=AGyH-Fsuqnj1lbg84GOF9bbhLrzHJQTKhg:40:286)
    at yd.v (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.uBO….O/m=platform_stable/rt=j/d=1/rs=AGyH-Fsuqnj1lbg84GOF9bbhLrzHJQTKhg:66:292)
```

**Comment by tansaku** [comment]
Kent beck notification failed today:

![failure](https://www.dropbox.com/s/rbyay3j2kdt77g8/Screenshot%202016-09-02%2016.53.26.png?dl=1)

```
MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details.
https://hangouts.google.com/hangouts/_/channel/test?VER=8&TYPE=xmlhttp&zx=g4eai3em8zpp Failed to load resource: the server responded with a status of 401 ()
43mv3wf545bcznv2kosqiox67ue:1 XMLHttpRequest cannot load https://hangouts.google.com/hangouts/_/channel/test?VER=8&TYPE=xmlhttp&zx=g4eai3em8zpp. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://talkgadget.google.com' is therefore not allowed access. The response had HTTP status code 401.
rs=AGyH-FvjxLr476K6iIxeIAs4gfpyuN6EGw:98 The MediaStream 'ended' event is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5730404371791872 for more details.
talkgadget.google.com/:552 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
https://images1-hangout-opensocial.googleusercontent.com/gadgets/proxy?url=…_f0458a7f051f6c3e7934c3f010ef4632.png&resize_h=32&resize_w=32&refresh=1052 Failed to load resource: the server responded with a status of 400 ()
rs=AGyH-FvjxLr476K6iIxeIAs4gfpyuN6EGw:4452 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
rs=AGyH-FvjxLr476K6iIxeIAs4gfpyuN6EGw:4452 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
ifr:242 Uncaught TypeError: a[c] is not a function
https://websiteone-production.herokuapp.com/hangouts/325154627 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
toolboxv2.js:888 'CanvasRenderingContext2D.webkitImageSmoothingEnabled' is deprecated. Please use 'CanvasRenderingContext2D.imageSmoothingEnabled' instead.
2https://websiteone-production.herokuapp.com/hangouts/325154627 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
rs=AGyH-FvjxLr476K6iIxeIAs4gfpyuN6EGw:1262 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.
websiteone-production.herokuapp.com/hangouts/325154627:1 PUT https://websiteone-production.herokuapp.com/hangouts/325154627 500 (Internal Server Error)
```

**Comment by tansaku** [comment]
@mtc2013 could we notify operator better when hangout connection fails?

**Comment by tansaku** [comment]
I started from firefox and it worked fine - then the WSO kick off immediately after using chrome and notification worked, for reference there are still a load of issues in the JS console when things work:

![usual errors](https://www.dropbox.com/s/32yy8nj4tpbgscq/Screenshot%202016-09-02%2017.01.14.png?dl=1)

and in text format:

```
https://hangouts.google.com/hangouts/_/channel/test?VER=8&TYPE=xmlhttp&zx=xksjlqypxx21 Failed to load resource: the server responded with a status of 401 ()
iiwzrlcw7vbgpiejnipw22jszue:1 XMLHttpRequest cannot load https://hangouts.google.com/hangouts/_/channel/test?VER=8&TYPE=xmlhttp&zx=xksjlqypxx21. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://talkgadget.google.com' is therefore not allowed access. The response had HTTP status code 401.
talkgadget.google.com/:371 MediaStreamTrack.getSources is deprecated. See https://www.chromestatus.com/feature/4765305641369600 for more details.
rs=AGyH-FvjxLr476K6iIxeIAs4gfpyuN6EGw:98 The MediaStream 'ended' event is deprecated and will be removed in M54, around October 2016. See https://www.chromestatus.com/features/5730404371791872 for more details.
talkgadget.google.com/:552 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
https://images1-hangout-opensocial.googleusercontent.com/gadgets/proxy?url=…2_f0458a7f051f6c3e7934c3f010ef4632.png&resize_h=32&resize_w=32&refresh=676 Failed to load resource: the server responded with a status of 400 ()
rs=AGyH-FvjxLr476K6iIxeIAs4gfpyuN6EGw:4452 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
rs=AGyH-FvjxLr476K6iIxeIAs4gfpyuN6EGw:4452 Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.
ifr:242 Uncaught TypeError: a[c] is not a function
plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.HQ8sIZfZ_Sc.O/m=platform_stable/rt=j/d=1/rs=AGyH-FuN7CXc_olSTN7B_DmcnJpb7KJs0A:42 Caught exception while dispatching event:
TypeError: Cannot read property 'authorize' of undefined
    at moritz.apps.toolbox.components.storage.mechanisms.Drive.authorize_ (https://hangouttoolboxv2.appspot.com/scripts/toolboxv2.js:1290:99)
    at moritz.apps.toolbox.components.storage.mechanisms.Drive.onApiReady_ (https://hangouttoolboxv2.appspot.com/scripts/toolboxv2.js:1288:407)
    at uc.handleEvent (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.HQ8…c.O/m=platform_stable/rt=j/d=1/rs=AGyH-FuN7CXc_olSTN7B_DmcnJpb7KJs0A:43:54)
    at yd.a.(anonymous function).a.(anonymous function) (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.HQ8….O/m=platform_stable/rt=j/d=1/rs=AGyH-FuN7CXc_olSTN7B_DmcnJpb7KJs0A:38:390)
    at jc (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.HQ8….O/m=platform_stable/rt=j/d=1/rs=AGyH-FuN7CXc_olSTN7B_DmcnJpb7KJs0A:41:660)
    at E (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.HQ8….O/m=platform_stable/rt=j/d=1/rs=AGyH-FuN7CXc_olSTN7B_DmcnJpb7KJs0A:40:286)
    at yd.v (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.HQ8….O/m=platform_stable/rt=j/d=1/rs=AGyH-FuN7CXc_olSTN7B_DmcnJpb7KJs0A:66:292)
    at nd (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.HQ8….O/m=platform_stable/rt=j/d=1/rs=AGyH-FuN7CXc_olSTN7B_DmcnJpb7KJs0A:63:295)
    at md (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.HQ8….O/m=platform_stable/rt=j/d=1/rs=AGyH-FuN7CXc_olSTN7B_DmcnJpb7KJs0A:61:414)
    at vd.ed.b (https://plus.google.com/_/scs/talk-static/_/js/k=wcs.platform_stable.en.HQ8…c.O/m=platform_stable/rt=j/d=1/rs=AGyH-FuN7CXc_olSTN7B_DmcnJpb7KJs0A:62:37)
rs=AGyH-FvjxLr476K6iIxeIAs4gfpyuN6EGw:1262 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.
```

**Comment by tansaku** [comment]
another fail that I noticed this time:

![](https://www.dropbox.com/s/3r3iqgjiwhp6w38/Screenshot%202016-09-06%2009.16.06.png?dl=1)

**Comment by tansaku** [comment]
worked immediately after from firefox so I think it might have been just a fail on our server for WSO.  I tried clicking through on that link and got:

```
dyno=web.1 connect=3ms service=546ms status=200 bytes=634
2016-09-06T08:19:04.233148+00:00 app[web.1]: Completed 200 OK in 533ms (ActiveRecord: 18.0ms)
2016-09-06T08:19:04.234156+00:00 app[web.1]: source=rack-timeout id=acabba87-0c50-4dc0-9ced-1bef35a4c2f3 wait=0ms timeout=20000ms service=539ms state=completed
2016-09-06T08:19:07.865580+00:00 heroku[web.1]: Process running mem=872M(169.7%)
2016-09-06T08:19:07.865815+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)
2016-09-06T08:19:13.157097+00:00 app[web.1]: source=rack-timeout id=e7bfab54-a984-4f8b-8dc0-c59a23d07f96 wait=3ms timeout=20000ms state=ready
2016-09-06T08:19:13.158981+00:00 app[web.1]: Started GET "/hangouts/325081532" for 86.145.234.60 at 2016-09-06 08:19:13 +0000
2016-09-06T08:19:13.162345+00:00 app[web.1]: Processing by StaticPagesController#show as HTML
2016-09-06T08:19:13.162385+00:00 app[web.1]:   Parameters: {"id"=>"hangouts/325081532"}
2016-09-06T08:19:13.272415+00:00 app[web.1]: Couldn't find StaticPage with 'id'=325081532
2016-09-06T08:19:13.272679+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:324:in `raise_record_not_found_exception!'
2016-09-06T08:19:13.272709+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:444:in `find_one'
2016-09-06T08:19:13.272734+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:423:in `find_with_ids'
2016-09-06T08:19:13.272776+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.6/lib/active_record/relation/finder_methods.rb:71:in `find'
2016-09-06T08:19:13.272779+00:00 app[web.1]: /app/vendor/bundle/ruby/2.3.0/gems/friendly_id-5.1.0/lib/friendly_id/finder_methods.rb:22:in `find'
2016-09-06T08:19:13.272818+00:00 app[web.1]: /app/app/controllers/static_pages_controller.rb:6:in `show'
2016-09-06T08:19:13.274028+00:00 app[web.1]:   Rendered static_pages/not_found.html.erb within layouts/application (0.6ms)
2016-09-06T08:19:13.275459+00:00 app[web.1]:   Rendered layouts/_meta_tags.html.erb (0.9ms)
2016-09-06T08:19:13.276626+00:00 app[web.1]:   Rendered layouts/_head.html.erb (2.3ms)
2016-09-06T08:19:13.285685+00:00 app[web.1]:   Rendered layouts/_flash.html.erb (0.3ms)
2016-09-06T08:19:13.285845+00:00 app[web.1]:   Rendered layouts/_navbar.html.erb (9.0ms)
2016-09-06T08:19:13.287942+00:00 app[web.1]:   Rendered layouts/_sponsors.html.erb (1.8ms)
2016-09-06T08:19:13.291854+00:00 app[web.1]:   Rendered layouts/_footer.html.erb (3.6ms)
2016-09-06T08:19:13.292296+00:00 app[web.1]: Completed 404 Not Found in 130ms (Views: 13.1ms | ActiveRecord: 9.7ms)
2016-09-06T08:19:13.293767+00:00 app[web.1]: source=rack-timeout id=e7bfab54-a984-4f8b-8dc0-c59a23d07f96 wait=3ms timeout=20000ms service=137ms state=completed
```

from the logs - even after a successful FF start - that's to this link https://websiteone-production.herokuapp.com/hangouts/325081532

**Comment by tansaku** [comment]
The FF instance connected successfully to https://websiteone-production.herokuapp.com/hangouts/325081704 hmmm
